//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtAddon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_STORE
    {
        public string Id { get; set; }
        public Nullable<int> Color_ { get; set; }
        public string Date { get; set; }
        public string From { get; set; }
        public string Message { get; set; }
        public Nullable<int> MessageFormat { get; set; }
        public Nullable<int> Type { get; set; }
        public string File { get; set; }
        public string Links { get; set; }
        public string RoomName { get; set; }
    }
}
